select DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as DATE_FORMAT, PRODUCT_ID, USER_ID, SALES_AMOUNT
from(
    select SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
     from ONLINE_SALE
    UNION
    select SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
     from OFFLINE_SALE
) as hap
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;